# Stage 1: Build the JAR
FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app
COPY requests_service/pom.xml .
COPY requests_service/src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run the JAR
FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*-all-jar-with-dependencies.jar app.jar

#ENTRYPOINT ["java", "-jar", "/app/app.jar"]
CMD ["java", "-jar", "/app/app.jar"]
#CMD ["ls", "/app/target"]